### PR TITLE
Add dockercompose

### PR DESCRIPTION
**Pull request by jmandel**

### CODE REVIEW

**Comment by jmandel** [comment]
One issue with running dev-ui as non-root:

```
dev-ui_1  | 🚨  Error writing to cache: EACCES: permission denied, mkdir '/usr/src/app/.cache'
dev-ui_1  | 🚨  Error writing to cache: EACCES: permission denied, mkdir '/usr/src/app/.cache'
dev-ui_1  | 🚨  Error writing to cache: EACCES: permission denied, mkdir '/usr/src/app/.cache'
```

User 1000 can't write to this location. I'm going to just widen the permissions on that directory (which isn't itself bind-mounted) to allow any user to write there. (I'm still not sure this setup will work for users other than 1000, since it looks like we're befitting from the fact that the `node` user already exists in this container as `1000`.)

**Comment by jmandel** [comment]
@madaster97 thanks again for contributing this. If you give the go-ahead, I'll merge into master.

**Comment by madaster97** [comment]
I just ran into the same issue. I think the best answer is to just keep `dev-ui` as root, but make sure it has read-only access to any bind-mounted folders. This would involve reverting my last commit, and changing the docker-compose.yaml to look something like this:
```yaml
volumes:
      - dist:/usr/src/app/dist
      - type: bind
        source: ./src
        target: /usr/src/app/src
```
This seems like a simpler solution. I think it's better to rely on Docker's volume functionality than try to chown our way out of this :) . With this, people could try to write into `src` from that container, but it would fail.
 
Otherwise, if we did go forward with chown, you can use the `USER` environment variable I have setup in `compose.env` to make that command dynamic.

**Comment by jmandel** [comment]
(I think you intended to include `read_only: true` in your bind mount options.)

> Otherwise, if we did go forward with chown, you can use the `USER` environment variable I have setup in compose.env to make that command dynamic.

I think you can't quite get there because you need the `USER` variable in the *build* process, and there's no clean way to feed `--env-file` values into the docker-compose build step (`args` is the closest you can get).

On the plus side, I haven't seriously looked at docker-compose in a couple of years, and it has only gotten better.

**Comment by madaster97** [comment]
Sounds good! Changes are in/tested. Will need a PR from my branch though.

I think we should revert this [commit](https://github.com/microsoft-healthcare-madison/health-wallet-demo/pull/41/commits/4e527968e26bb6fa2da5ae40073c8917a60565d2) then.

**Comment by jmandel** [comment]
Sounds good! If you do a PR from your branch at https://github.com/madaster97/health-wallet-demo/blob/6db726466c441b68f8cc0a0f6272634419894a99/docker-compose.yaml did you still mean to add a read-only bind mount for `./src` in `dev-ui`?

**Comment by jmandel** [comment]
Yay -- thanks again for your help with this, and sorry for the round-about in getting it merged @madaster97!

**Pull request merged**
